source: .
destination: ./_site
safe: true
timezone: Europe/Copenhagen
encoding: utf-8
name: mathmagicians
markdown: kramdown
baseurl: ""
url: "http://www.mathmagicians.dk"
markdown: kramdown
theme: minima
backend: false