version: '3.4'
services:
  devserver:
    container_name: mathmagicians-devserver
    image: mathmagicians/mathmagicians_build
    command: ["npm", "run", "serve"]
    working_dir: /tmp/services/frontend
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
        - type: bind
          source: ./
          target: /tmp
    networks:
      - mathmagicians

networks:
  mathmagicians:
    driver: bridge
